version: '3.8'

services:
  backend:
    build:
      context: ./food_freshness_project
      dockerfile: Dockerfile
    container_name: ffm_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: always

  frontend:
    build:
      context: ./food-freshness-platform
      dockerfile: Dockerfile
    container_name: ffm_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    restart: always
