export const USER_ROLES = {
  CONSUMER: 'Consumer',
  RETAIL_MANAGER: 'Retail Manager',
  WAREHOUSE_OPERATOR: 'Warehouse Operator',
  QUALITY_INSPECTOR: 'Food Quality Inspector',
  ADMINISTRATOR: 'Administrator',
};

export const CATEGORIES = [
  { id: 'fruits', name: 'Fruits', icon: 'Apple', color: '#10B981', itemCount: 142 },
  { id: 'vegetables', name: 'Vegetables', icon: 'Carrot', color: '#84CC16', itemCount: 189 },
  { id: 'dairy', name: 'Dairy', icon: 'Milk', color: '#06B6D4', itemCount: 95 },
  { id: 'meat', name: 'Meat', icon: 'Drumstick', color: '#EF4444', itemCount: 64 },
  { id: 'seafood', name: 'Seafood', icon: 'Fish', color: '#3B82F6', itemCount: 48 },
  { id: 'bakery', name: 'Bakery', icon: 'Croissant', color: '#F59E0B', itemCount: 82 },
  { id: 'packaged', name: 'Packaged Food', icon: 'Package', color: '#8B5CF6', itemCount: 210 },
  { id: 'beverages', name: 'Beverages', icon: 'CupSoda', color: '#EC4899', itemCount: 115 },
];

export const FRESHNESS_GRADES = {
  FRESH: { label: 'Fresh', color: '#10B981', bgClass: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40' },
  GOOD: { label: 'Good', color: '#84CC16', bgClass: 'bg-lime-500/20 text-lime-300 border-lime-500/40' },
  ACCEPTABLE: { label: 'Acceptable', color: '#06B6D4', bgClass: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40' },
  NEAR_SPOILAGE: { label: 'Near Spoilage', color: '#F59E0B', bgClass: 'bg-amber-500/20 text-amber-300 border-amber-500/40' },
  SPOILED: { label: 'Spoiled', color: '#EF4444', bgClass: 'bg-rose-500/20 text-rose-300 border-rose-500/40' },
};

export const MOCK_INVENTORY = [
  {
    id: 'FBD-9041',
    name: 'Organic Cavendish Bananas',
    category: 'Fruits',
    batchId: 'BATCH-2026-089',
    supplier: 'GreenHarvest Orchards',
    arrivalDate: '2026-07-26',
    expiryDate: '2026-08-04',
    warehouse: 'Cold Bay Alpha-2',
    quantity: '450 kg',
    freshnessScore: 92,
    shelfLifeDays: 5,
    status: 'FRESH',
    storageTemp: '13.5°C',
    storageHumidity: '88%',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    colorScore: 94,
    textureScore: 90,
    moldRisk: '0.2%',
    bruisingRisk: '2.1%',
  },
  {
    id: 'FBD-9042',
    name: 'Fresh Strawberries',
    category: 'Fruits',
    batchId: 'BATCH-2026-092',
    supplier: 'BerryFresh Farms',
    arrivalDate: '2026-07-28',
    expiryDate: '2026-08-01',
    warehouse: 'Cold Bay Alpha-1',
    quantity: '120 kg',
    freshnessScore: 68,
    shelfLifeDays: 2,
    status: 'NEAR_SPOILAGE',
    storageTemp: '3.2°C',
    storageHumidity: '92%',
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
    colorScore: 72,
    textureScore: 65,
    moldRisk: '12.4%',
    bruisingRisk: '18.7%',
  },
  {
    id: 'FBD-9043',
    name: 'Pasture-Raised Whole Milk',
    category: 'Dairy',
    batchId: 'BATCH-2026-081',
    supplier: 'Alpine Dairy Co.',
    arrivalDate: '2026-07-24',
    expiryDate: '2026-08-08',
    warehouse: 'Chiller Unit Delta',
    quantity: '800 L',
    freshnessScore: 88,
    shelfLifeDays: 9,
    status: 'GOOD',
    storageTemp: '2.8°C',
    storageHumidity: '65%',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80',
    colorScore: 95,
    textureScore: 89,
    moldRisk: '0.0%',
    bruisingRisk: '0.0%',
  },
  {
    id: 'FBD-9044',
    name: 'Wild Atlantic Salmon Fillet',
    category: 'Seafood',
    batchId: 'BATCH-2026-095',
    supplier: 'Oceanic Prime Logistics',
    arrivalDate: '2026-07-29',
    expiryDate: '2026-08-03',
    warehouse: 'Deep Freeze - Bay 3',
    quantity: '220 kg',
    freshnessScore: 96,
    shelfLifeDays: 5,
    status: 'FRESH',
    storageTemp: '-1.5°C',
    storageHumidity: '85%',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    colorScore: 98,
    textureScore: 95,
    moldRisk: '0.1%',
    bruisingRisk: '1.0%',
  },
  {
    id: 'FBD-9045',
    name: 'Artisanal Sourdough Bread',
    category: 'Bakery',
    batchId: 'BATCH-2026-099',
    supplier: 'Heritage Hearth Bakeries',
    arrivalDate: '2026-07-29',
    expiryDate: '2026-08-02',
    warehouse: 'Ambient Zone B',
    quantity: '150 units',
    freshnessScore: 84,
    shelfLifeDays: 3,
    status: 'GOOD',
    storageTemp: '21.0°C',
    storageHumidity: '50%',
    image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=600&q=80',
    colorScore: 88,
    textureScore: 82,
    moldRisk: '1.5%',
    bruisingRisk: '0.5%',
  },
  {
    id: 'FBD-9046',
    name: 'Hass Avocado Pack',
    category: 'Vegetables',
    batchId: 'BATCH-2026-074',
    supplier: 'SunValley Produce',
    arrivalDate: '2026-07-20',
    expiryDate: '2026-07-30',
    warehouse: 'Ripening Room 2',
    quantity: '340 kg',
    freshnessScore: 42,
    shelfLifeDays: 0,
    status: 'SPOILED',
    storageTemp: '18.5°C',
    storageHumidity: '75%',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=600&q=80',
    colorScore: 40,
    textureScore: 35,
    moldRisk: '45.2%',
    bruisingRisk: '62.0%',
  },
];

export const MOCK_TELEMETRY = {
  temperature: { current: 3.4, ideal: 3.5, min: 2.0, max: 5.0, status: 'Optimal', unit: '°C' },
  humidity: { current: 87.5, ideal: 85.0, min: 80.0, max: 92.0, status: 'Optimal', unit: '%' },
  airCirculation: { current: 4.2, ideal: 4.0, min: 3.0, max: 5.0, status: 'Good', unit: 'm/s' },
  lightExposure: { current: 45, ideal: 30, min: 10, max: 100, status: 'Warning', unit: 'lux' },
  storageDuration: { current: 4.2, maxRecommended: 7.0, status: 'Safe', unit: 'Days' },
};

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-1',
    title: 'Expiry Alert: Fresh Strawberries',
    message: 'Batch BATCH-2026-092 in Cold Bay Alpha-1 has only 2 days remaining. Immediate clearance recommended.',
    type: 'warning',
    timestamp: '10 minutes ago',
    unread: true,
  },
  {
    id: 'notif-2',
    title: 'Spoilage Threshold Triggered',
    message: 'Hass Avocado Pack (FBD-9046) detected spoilage score above 50%. Quarantined automatically.',
    type: 'danger',
    timestamp: '45 minutes ago',
    unread: true,
  },
  {
    id: 'notif-3',
    title: 'AI Model Inspection Completed',
    message: 'Batch BATCH-2026-095 (Salmon Fillets) scored 96% Freshness score with 99.4% prediction confidence.',
    type: 'success',
    timestamp: '2 hours ago',
    unread: false,
  },
  {
    id: 'notif-4',
    title: 'Light Exposure Drift Alert',
    message: 'Chiller Unit Delta light sensor detected 45 lux (15 lux above ideal setting).',
    type: 'info',
    timestamp: '5 hours ago',
    unread: false,
  },
];

export const MOCK_SYSTEM_HEALTH = {
  activeUsers: 1482,
  apiLatency: '42ms',
  apiStatus: '99.98% Operational',
  predictionRequestsToday: 34910,
  storageUsage: '1.42 TB / 5 TB',
  gpuLoad: '34%',
};
