import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { 
  FileText, 
  Download, 
  Calendar, 
  Sparkles, 
  CheckCircle2, 
  ShieldCheck, 
  Eye, 
  Printer,
  FileDown
} from 'lucide-react';

export const ReportsPage: React.FC = () => {
  const { qualityReports, addToast } = useApp();
  const [selectedReportType, setSelectedReportType] = useState('All');

  const handleDownload = (title: string, format: string) => {
    const sampleContent = `========================================================
FRESHSENSE AI - OFFICIAL QUALITY AUDIT EXPORT
========================================================
Report Title: ${title}
Generated Date: ${new Date().toLocaleString()}
Compliance Standard: ISO 22000 / HACCP Produce Safety
Export Format: ${format}

SUMMARY OVERVIEW
--------------------------------------------------------
- Active Inventory Batches Assessed: 12
- Mean Freshness Index: 91.2 / 100
- Cold Chain Violation Incidents: 0
- Projected Spoilage Mitigation: 94.8%

AUDIT TRAIL VERIFICATION
--------------------------------------------------------
System Generated by FreshSense AI Neural Spoilage Engine.
`;

    const blob = new Blob([sampleContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${title.replace(/\s+/g, '-')}.${format.toLowerCase()}`;
    link.click();
    URL.revokeObjectURL(url);

    addToast({
      type: 'success',
      title: 'Report Downloaded',
      message: `${title} exported as ${format}.`
    });
  };

  return (
    <div id="reports-management-page" className="space-y-6">
      {/* Header */}
      <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <span className="p-2.5 rounded-2xl bg-teal-500/10 text-teal-600 dark:text-teal-400">
            <FileText className="w-5 h-5" />
          </span>
          <div>
            <h1 className="text-xl font-black text-slate-900 dark:text-white">
              Quality & Regulatory Compliance Reports
            </h1>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Generate and export official HACCP compliance audits, freshness logs, and waste reduction statements.
            </p>
          </div>
        </div>

        <button
          onClick={() => handleDownload('Master Produce Audit', 'PDF')}
          className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs shadow-md transition-all shrink-0"
        >
          <FileDown className="w-4 h-4" />
          <span>Generate Full Audit Dossier</span>
        </button>
      </div>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {qualityReports.map((report) => (
          <div
            key={report.id}
            className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col justify-between space-y-4 hover:shadow-md transition-shadow"
          >
            <div className="space-y-3">
              <div className="flex items-start justify-between gap-2">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                    {report.type}
                  </span>
                  <h3 className="text-sm font-bold text-slate-900 dark:text-white mt-0.5">
                    {report.title}
                  </h3>
                </div>
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                  {report.format} • {report.fileSize}
                </span>
              </div>

              {report.summary && typeof report.summary === 'object' ? (
                <div className="grid grid-cols-2 gap-2 p-3 bg-slate-50 dark:bg-slate-800/60 rounded-xl text-[11px]">
                  <div>
                    <span className="text-slate-400">Total Scanned:</span>{' '}
                    <span className="font-bold text-slate-700 dark:text-slate-200">{report.summary.totalScanned} items</span>
                  </div>
                  <div>
                    <span className="text-slate-400">Avg Freshness:</span>{' '}
                    <span className="font-bold text-emerald-600 dark:text-emerald-400">{report.summary.avgFreshness}/100</span>
                  </div>
                  <div>
                    <span className="text-slate-400">Spoilage Rate:</span>{' '}
                    <span className="font-bold text-amber-600 dark:text-amber-400">{report.summary.spoilageRate}%</span>
                  </div>
                  <div>
                    <span className="text-slate-400">Waste Averted:</span>{' '}
                    <span className="font-bold text-teal-600 dark:text-teal-400">{report.summary.wasteAvertedKg} kg</span>
                  </div>
                </div>
              ) : (
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                  {String(report.summary || 'Summary generated by FreshSense Telemetry Engine.')}
                </p>
              )}

              <div className="text-[11px] text-slate-400 flex items-center gap-2 pt-1">
                <Calendar className="w-3.5 h-3.5 text-slate-400" />
                <span>Generated: {report.generatedDate} • Range: {report.dateRange} • By: {report.generatedBy}</span>
              </div>
            </div>

            <div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-end gap-2">
              <button
                onClick={() => handleDownload(report.title, 'PDF')}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 text-slate-700 dark:text-slate-200 font-bold text-xs transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                <span>PDF</span>
              </button>

              <button
                onClick={() => handleDownload(report.title, 'CSV')}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 text-slate-700 dark:text-slate-200 font-bold text-xs transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                <span>CSV</span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
